# Generated by Django 5.0.6 on 2024-05-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioconcurso',
            name='nrocomprobante',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
