# Generated by Django 5.0.6 on 2024-05-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0002_formularioconcurso_nrocomprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioconcurso',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
