# Generated by Django 5.0.6 on 2024-05-12 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0003_alter_formularioconcurso_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioconcurso',
            name='nombres',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios', regex='^[a-zA-Z ]*$')]),
        ),
    ]
