# Generated by Django 5.0.6 on 2024-05-12 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0005_alter_formularioconcurso_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioconcurso',
            name='apellidos',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Apellido Invalido', regex='^[a-zA-Zñ ]*$')]),
        ),
    ]
