# Generated by Django 5.0.6 on 2024-05-12 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0007_alter_formularioconcurso_apellidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioconcurso',
            name='nombres',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nombre Invalido', regex='^[a-zA-ZñÑ ]*$')]),
        ),
    ]
