# Generated by Django 5.0.6 on 2024-05-13 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0011_remove_formularioconcurso_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioconcurso',
            name='telefono',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(12)]),
            preserve_default=False,
        ),
    ]
