# Generated by Django 5.0.6 on 2024-05-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0013_alter_formularioconcurso_nrocomprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioconcurso',
            name='nrocomprobante',
            field=models.CharField(max_length=15),
        ),
    ]
