# Generated by Django 5.0.6 on 2024-05-14 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0014_alter_formularioconcurso_nrocomprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioconcurso',
            name='nombres',
            field=models.CharField(max_length=50),
        ),
    ]
