# Generated by Django 5.0.6 on 2024-05-14 21:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0015_alter_formularioconcurso_nombres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioconcurso',
            name='apellidos',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Apellido Inválido', regex='^[a-zA-ZñÑ ]*$')]),
        ),
        migrations.AlterField(
            model_name='formularioconcurso',
            name='nrocomprobante',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
