# Generated by Django 5.0.6 on 2024-05-14 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appformulario', '0016_alter_formularioconcurso_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioconcurso',
            name='nrocomprobante',
            field=models.CharField(max_length=15),
        ),
    ]
